### ISSUE TITLE
Icon request: Slack & Telegram

### ISSUE THREAD

**Issue by Revod** [xenlism/wildfire#27]
Hope get that icon with your icon pack. love you icons-theme

**Comment by xenlism** [comment]
Telegram Exits

**Comment by Revod** [comment]
is this?
![captura de pantalla de 2015-10-10 10 42 50](https://cloud.githubusercontent.com/assets/10109689/10411806/ceaa552c-6f3b-11e5-9077-3148c337ec06.png)
