### ISSUE TITLE
Icons: Haskell & Scala

### ISSUE THREAD

**Issue by strelec** [xenlism/wildfire#29]
Haskell: Currently, the icon is an ugly yellow collor with angled brackets. It immediately associates to HTML. The more standard version would be blue with a haskell logo: https://www.haskell.org/static/img/logo.png

Scala: The icon is missing. I propose a red icon with Scala logo.

**Comment by xenlism** [comment]
please show original

**Comment by strelec** [comment]
I have noticed haskell is just a symobolic link to Scheme:

https://github.com/xenlism/wildfire/blob/master/icons/Xenlism-Wildfire/Mimes/text-x-scheme.svg

**Comment by xenlism** [comment]
You love this?

**Comment by strelec** [comment]
No, Haskell should have a different icon than Scheme, they are two completely different programming languages.

**Comment by xenlism** [comment]
file --mime-type /path/to/file

**Comment by strelec** [comment]
text/x-scala-source

**Comment by xenlism** [comment]
closed
