### ISSUE TITLE
Installation path does not respect unix structure

### ISSUE THREAD

**Issue by frague59** [xenlism/wildfire#3]
Hi, 

I use wildfire iconset, and I have seen the installation path through the wget / curl path does not respect https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

The icon set should be installed into the /usr/local/share/icons folder, because it is not part of distribution.
Good job at all !

**Comment by frague59** [comment]
mistake... does not work with gnome ... sorry !

**Comment by xenlism** [comment]
You use debian right?

**Comment by frague59** [comment]
Yes

**Comment by frague59** [comment]
I'm the guy with strange hang-outs with the icon set

**Comment by xenlism** [comment]
Any linux distro support install icon themes to /usr/share/icons.
I use debian before.

**Comment by xenlism** [comment]
Are you test this?

**Comment by frague59** [comment]
I did test /usr/local/share and gnome hangs out...

**Comment by frague59** [comment]
... so I close the ticket, because it is a mistake, even if it looks like a policy breaking...
Sorry about that !

**Comment by xenlism** [comment]
ok
