### ISSUE TITLE
README: What are Monday, Thursday, Friday (...), and how to make it automatically switch every day.

### ISSUE THREAD

**Issue by strelec** [xenlism/wildfire#30]
I think this crucial piece of information is missing. Explain more in depth what is the point of that many versions.

Moreover, I see no difference among the Day, MidNight and Night versions.

I hope all the best for this icon theme, and wishing it to become de-facto standard just like Arc theme is.

**Comment by xenlism** [comment]
Night - Dark theme
Mid Night - Darkest theme
Day - Light Theme
Mon-Sun Day , Color Of the day.

**Comment by strelec** [comment]
Not to me, please add that to the README, for others.

**Comment by xenlism** [comment]
Ok, I will add ASAP.
