### ISSUE TITLE
Problem with the icon bar size

### ISSUE THREAD

**Issue by Revod** [xenlism/wildfire#31]
How I can fix this? Using Elementary OS Freya (Based Ubuntu 14.04) ![captura de pantalla de 2015-10-16 00 44 18](https://cloud.githubusercontent.com/assets/10109689/10534239/76f2b992-739f-11e5-8439-c3fc30e8ec04.png)

**Comment by xenlism** [comment]
or your report

**Comment by Revod** [comment]
what?
