### ISSUE TITLE
Create Tags

### ISSUE THREAD

**Issue by jubalh** [xenlism/wildfire#37]
It would make packaging your theme a lot easier if you could please use tags.
Adding nice ChangeLongs into the tags description.

For an example, please see what [arc-theme](https://github.com/horst3180/arc-theme/releases) does.

**Comment by xenlism** [comment]
Thank you.
I will fix ASAP.

**Comment by jubalh** [comment]
Would be good to first do it and then close :) Otherwise you might forget it.

**Comment by xenlism** [comment]
I not forget.but now I still work. I can't release any version b'cuz it not minor change.

Nattapong Pullkhow <ixenatt@gmail.com>

เมื่อ 26 เม.ย. 2561 เวลา 01:04 Michael Vetter <notifications@github.com> เขียน:
