### ISSUE TITLE
Icon request: Rust programming language

### ISSUE THREAD

**Issue by fbruetting** [xenlism/wildfire#38]
Hi, love your mime icons! Would you please provide a rusty rust icon, too?

Here's the official Logo, if it helps:
https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg

**Comment by fb87** [comment]
Would be nice if you can provide an icon for the according „crates“ (*.rlib) also. :)

Maybe some colors like this?
http://www.cargocontainerhq.com/images/used-cargo-containers.jpg

**Comment by xenlism** [comment]
Thank you.
I will work ASAP.

**Comment by fbruetting** [comment]
You’re alive! Great – can’t wait to see further improvements! 😎

**Comment by xenlism** [comment]
I need your help.
first for mimetype.
file --mime-type /path/to/file 
second icons. 
cat /usr/share/applications/{ name of rusticon.desktop} grep | Icon=

**Comment by fbruetting** [comment]
`lib.rs: text/x-c`

There is no Rust application, there’s just `rustc` and `cargo` which both being terminal programs.

**Comment by fbruetting** [comment]
Would you also look into https://github.com/xenlism/wildfire/issues/43 again, as this was targeted against the `.jl` file icons, and not against the application? :)

**Comment by xenlism** [comment]
This file ?
![artboard 1](https://user-images.githubusercontent.com/13846221/39397380-86685446-4b28-11e8-9ee4-0b1ea579bc90.png)
text-x-c

**Comment by xenlism** [comment]
please answer me.

**Comment by fbruetting** [comment]
Today in the evening. I was not at home this weekend.


Am 30.04.2018 11:26 schrieb Nattapong Pullkhow <notifications@github.com>:

please answer me.

**Comment by fbruetting** [comment]
Ok, so C source and header files are `text/plain` (and the correct icons are shown), whereas Rust files are shown as `text/x-c` with a standard text file icon.

![bildschirmfoto von 2018-04-30 20-29-49](https://user-images.githubusercontent.com/10520767/39443579-50ae2ee6-4cb5-11e8-8623-90fe7aa214dc.png)

**Comment by xenlism** [comment]
Or I will try.

**Comment by xenlism** [comment]
You have to try.
And I will do for JL file.

**Comment by xenlism** [comment]
please try and tell me.
now I add .rs ..jl

**Comment by fbruetting** [comment]
Now all files have the same standard yellow text icon, even the C source/header file icons don’t apply anymore.

**Comment by fbruetting** [comment]
Seems `file` is not that good – if I use `xdg-mime query filetype <FILE>` instead, I get
```
text/x-csrc (C source)
text/x-chdr (C header)
text/rust (Rust)
text/plain (Julia)
```

**Comment by xenlism** [comment]
please try again

**Comment by fbruetting** [comment]
Now just the C header file got a new logo. Maybe the routine for this doesn’t detect the MIME type for Rust applications. I see if I can look into that, the next days.

**Comment by xenlism** [comment]
I try to fix it but wont work.
