### ISSUE TITLE
Icon request: Julia language

### ISSUE THREAD

**Issue by fbruetting** [xenlism/wildfire#43]
Best scientific general purpose language, would be nice if it can get a custom icon, too!

Language Logo:
https://upload.wikimedia.org/wikipedia/commons/6/69/Julia_prog_language.svg

**Comment by xenlism** [comment]
Added

**Comment by fbruetting** [comment]
Ah, I actually meant the MIME type, i.e. files ending with `*.jl`. :/

**Comment by xenlism** [comment]
text/plain I think it's impossible.

**Comment by fbruetting** [comment]
Works fine for C source and header files, which both are `text/plain`, for example.

**Comment by fbruetting** [comment]
I requested a media type for Julia files in https://github.com/JuliaLang/julia/issues/26947. Think you can use `text/julia`, should then work as soon as implemented.
