### ISSUE TITLE
Icon Request: Otter Browser

### ISSUE THREAD

**Issue by m4sk1n** [xenlism/wildfire#47]
- [Otter Browser](https://github.com/OtterBrowser/otter-browser)
- Project that aims to recreate the best aspects of the classic Opera (12.x) UI using Qt5
- `Icon=otter-browser`
![10384419](https://cloud.githubusercontent.com/assets/21127288/24331480/9c76167e-1235-11e7-9012-0a64312e877f.png)

**Comment by xenlism** [comment]
I will Do ASAP.
Thank you.

**Comment by xenlism** [comment]
Closed Added
