### ISSUE TITLE
yumex-dnf .svg has a space in the filename

### ISSUE THREAD

**Issue by filipkemuel** [xenlism/wildfire#48]
The icon yumex-dnf in the Apps folder has a space before the .svg - this makes gtk.update-icon-cache throw an error.

Renaming it so that it does not have a space fixes this. And actually also fixes it so that the icon is actually shown for yumex ;)

```bash
mv Apps/yumex-dnf\ .svg Apps/yumex-dnf.svg
```

**Comment by xenlism** [comment]
Thank you.

**Comment by xenlism** [comment]
Fixed
