### ISSUE TITLE
A lot of gnome apps is missing icons

### ISSUE THREAD

**Issue by filipkemuel** [xenlism/wildfire#49]
A lot of the icons for the core Gnome apps no longer show up because Gnome decided to rename them.

Current name in theme | The new Gnome names
------------ | -------------
gnome-photos.svg | org.gnome.Photos.svg.svg
gnome-books.svg | org.gnome.Books.svg
cheese.svg | org.gnome.Cheese.svg
gnome-documents.svg | org.gnome.Documents.svg
nautilus.svg | org.gnome.Nautilus.svg
gnome-calendar.svg| org.gnome.Calendar.svg
addressbook.svg | org.gnome.Contacts.svg
gnome-maps.svg | org.gnome.Maps.svg
org.gnome.Weather.Application.svg | org.gnome.Weather.svg
totem.svg | org.gnome.Totem.svg
builder.svg | org.gnome.Builder.svg
gnome-clocks.svg | org.gnome.clocks.svg
polari.svg | org.gnome.Polari.svg
gnome-software.svg | org.gnome.Software.svg
task.svg | org.gnome.Todo

This is causing problems in many icon-themes so I made a bash script that attempts to fix the names for the icon theme that is currently chosen in gnome. It will fix this theme and many others.

[gnome-icon-fixer.txt](https://github.com/xenlism/wildfire/files/1253340/gnome-icon-fixer.txt)

**Comment by Barracuda77** [comment]
Hi this is very helpful
on centos 7.4 they just updated to GNOME Shell 3.22.3 and that changed the system file manager icon.
would you happen to know the new name?
and am a bit new to Linux, would you be able to point me where to find and rename those icons
as am not able to run that gnome-icon-fixer file 

Thanks a lot
Regards

**Comment by koma111** [comment]
Useful script! Would be even better if it created symlinks instead of renaming the files.

**Comment by filipkemuel** [comment]
@Barracuda77
I didn't get your question at first because the icon is already listed in my post above. But realized that you probably didn't  know that the filemanage is 'Nautilus'

@koma11
Eh?? But that is exactly what the script does.. It creates symlinks..

**Comment by xenlism** [comment]
Fixed Thank you

**Comment by pyaazkaparatha** [comment]
I am unable to use the script to fix icons. I want to make symlinks in all the installed themes.
