### ISSUE TITLE
Wrong icon for `application/x-partial-download`

### ISSUE THREAD

**Issue by fbruetting** [xenlism/wildfire#56]
`*.part` files (e.g. unfinished Firefox downloads) with `application/x-partial-download` media type currently have the `application-apk.svg`/`application-software.svg`/`application-x-pak.svg`/`gnome-package.svg`/`package.svg`/`package-x-generic.svg` icon assigned. Ok, the icon somehow contains a loading bar, but still, the icon addresses more applications or IDE-like software instead of file fragments (which don’t have to be applications themselves).

I assume some catchall-like rule for `application/*` causes this, am I right?

**Comment by xenlism** [comment]
.part file not change to package file but other changed
