### ISSUE TITLE
Telephone icon

### ISSUE THREAD

**Issue by fravaccaro** [xenlism/wildfire#68]
Good evening,

I felt in love with wildfire as it has a sexy MeeGo feeling and I've been porting it on Sailfish OS, but I ran into an issue: the lack of a proper telephone icon (for the dialer app).

Has it been planned for the following releases? It's so far the only stop issue to me to complete my porting.

Br,

Fra

**Comment by xenlism** [comment]
I will make it ASAP.

ส่งจาก iPad ของฉัน

เมื่อ 12 ต.ค. 2561 เวลา 01:58 Fra <notifications@github.com> เขียน:

**Comment by fravaccaro** [comment]
Thank you so much!

In the meanwhile, I completed my porting, there's a partial result :)

![screenshot-18-10-13-03-43-10](https://user-images.githubusercontent.com/12102227/46899933-8b2bf780-ce9a-11e8-8e12-c6ac5a0b8596.png)

**Comment by xenlism** [comment]
Good job.

ส่งจาก iPad ของฉัน

เมื่อ 13 ต.ค. 2561 เวลา 08:47 Fra <notifications@github.com> เขียน:

**Comment by xenlism** [comment]
closed check it out 
https://github.com/xenlism/wildfire/blob/master/icons/Xenlism-Wildfire/Apps/telephone.svg
