### ISSUE TITLE
Reddit icon

### ISSUE THREAD

**Issue by fravaccaro** [xenlism/wildfire#71]
I'm not sure how to PR, I made a Reddit icon which I hope could be useful.

Br,

Fra
[reddit.zip](https://github.com/xenlism/wildfire/files/2799119/reddit.zip)

**Comment by xenlism** [comment]
Can you accept GPL?

**Comment by xenlism** [comment]
![reddit](https://user-images.githubusercontent.com/13846221/51789054-9855c380-21b7-11e9-9044-c0bc1efb3adf.png)
I already Redesign.

**Comment by fravaccaro** [comment]
Looks great!

Yup, GPL is fine for me :)

**Comment by xenlism** [comment]
Ok

**Comment by xenlism** [comment]
https://github.com/xenlism/wildfire/blob/master/icons/Xenlism-Wildfire/Apps/reddit.svg
